#!/system/bin/sh
# Deferred post-boot tasks only — mount pipeline runs in metamount.sh.
MODDIR="${0%/*}"

# Single-instance guard (atomic via noclobber)
LOCKFILE="/dev/zeromount_lock"
( set -o noclobber; echo $$ > "$LOCKFILE" ) 2>/dev/null || exit 0
trap 'rm -f "$LOCKFILE"' EXIT
trap 'exit 0' INT TERM

. "$MODDIR/common.sh"
[ -z "$ABI" ] && exit 1
[ -x "$BIN" ] || exit 1

if [ -f /data/adb/zeromount/.verbose ]; then
    echo "zeromount: restoring verbose mode from marker" > /dev/kmsg
    $BIN log level 3
fi

# --- WebUI zero-latency init: inline all data at boot ---
WEBROOT="$MODDIR/webroot"
if [ -d "$WEBROOT" ]; then
    CACHE=$("$BIN" webui-init 2>/dev/null)
    if [ -n "$CACHE" ]; then
        echo "$CACHE" > "$WEBROOT/cache.json" 2>/dev/null

        # Extract system accent color (same query the WebUI would make via ksu.exec)
        ACCENT=""
        THEME_RAW=$(settings get secure theme_customization_overlay_packages 2>/dev/null)
        if [ -n "$THEME_RAW" ]; then
            ACCENT=$(echo "$THEME_RAW" | grep -oE '#?[0-9a-fA-F]{6,8}' | head -1)
            [ -n "$ACCENT" ] && case "$ACCENT" in '#'*) ;; *) ACCENT="#$ACCENT" ;; esac
            # Trim to 6-char hex
            ACCENT=$(echo "$ACCENT" | sed 's/^\(#.\{6\}\).*/\1/')
        fi

        # Read pre-bundled locale data (generated by Vite build)
        LOCALES=""
        [ -f "$WEBROOT/locales-bundle.json" ] && LOCALES=$(cat "$WEBROOT/locales-bundle.json" 2>/dev/null)

        LOCALE_CODE=$(getprop persist.sys.locale 2>/dev/null || getprop ro.product.locale 2>/dev/null || echo "en")
        LOCALE_CODE=$(printf '%s' "$LOCALE_CODE" | sed 's/_/-/g')
        case "$LOCALE_CODE" in
            zh-Hans*|zh-CN*) LOCALE_CODE="zh-CN" ;;
            zh-Hant*|zh-TW*) LOCALE_CODE="zh-TW" ;;
            pt-BR*) LOCALE_CODE="pt-BR" ;;
            pt*) LOCALE_CODE="pt-PT" ;;
            *-*) LOCALE_CODE="${LOCALE_CODE%%-*}" ;;
        esac

        {
            printf 'window.__ZM_CACHE__=%s;\n' "$CACHE"
            [ -n "$ACCENT" ] && printf 'window.__ZM_ACCENT__="%s";\n' "$ACCENT"
            [ -n "$LOCALES" ] && printf 'window.__ZM_LOCALES__=%s;\n' "$LOCALES"
            printf 'window.__ZM_LOCALE_CODE__="%s";\n' "$LOCALE_CODE"
        } > "$WEBROOT/zm-init.js"

        # Inject script reference (idempotent: skip if already present)
        if ! grep -q 'zm-init.js' "$WEBROOT/index.html" 2>/dev/null; then
            sed -i 's|</head>|<script src="zm-init.js"></script></head>|' "$WEBROOT/index.html"
        fi
    fi
fi

# Track background PIDs for cleanup
_bg_pids=""

# Device-wide boot monitors
{
    "$BIN" guard watch-boot 2>/dev/null || \
        echo "zeromount: boot timeout, guard recovery" > /dev/kmsg 2>/dev/null
} &
_bg_pids="$_bg_pids $!"

{
    "$BIN" guard watch-zygote 2>/dev/null || \
        echo "zeromount: zygote unstable, guard recovery" > /dev/kmsg 2>/dev/null
} &
_bg_pids="$_bg_pids $!"

"$BIN" guard watch-systemui 2>/dev/null &
_bg_pids="$_bg_pids $!"

# Manual safe mode: volume key combo check every second until boot completes
if command -v getevent >/dev/null 2>&1; then
    {
        while [ "$(getprop sys.boot_completed)" != "1" ]; do
            _keys=$(timeout 1 getevent -lq 2>/dev/null || true)
            if echo "$_keys" | grep -q 'KEY_VOLUMEDOWN.*DOWN' && \
               echo "$_keys" | grep -q 'KEY_VOLUMEUP.*DOWN'; then
                echo "zeromount: vol-up+down safe mode triggered (service), running guard recovery" > /dev/kmsg 2>/dev/null
                "$BIN" guard recover 2>/dev/null
                break
            fi
        done
    } &
    _bg_pids="$_bg_pids $!"
fi

# Late-loaded modules miss the mount window before zygote; restart framework
# so apps see the mounts. Also honor explicit user toggle.
RESTART_FW=$("$BIN" config get mount.restart_framework 2>/dev/null)
if [ "$RESTART_FW" = "true" ] || [ "$KSU_LATE_LOAD" = "1" ]; then
    echo "zeromount: restarting framework (restart_fw=$RESTART_FW late_load=${KSU_LATE_LOAD:-0})" > /dev/kmsg 2>/dev/null
    stop; start
fi

PROP_SPOOF=$("$BIN" config get brene.prop_spoofing 2>/dev/null)

if [ "$PROP_SPOOF" = "true" ]; then
    # External SUSFS module handles props — defer (matches mod.rs:22-25)
    _ext_susfs="/data/adb/zeromount/flags/external_susfs"
    _ext_val=""
    [ -f "$_ext_susfs" ] && _ext_val=$(cat "$_ext_susfs" 2>/dev/null)
    _ext_val=$(echo "$_ext_val" | tr -d '[:space:]')

    if [ -n "$_ext_val" ] && [ "$_ext_val" != "none" ]; then
        echo "zeromount: prop spoofing deferred to external module" > /dev/kmsg 2>/dev/null
    elif [ ! -x "$RP" ]; then
        echo "zeromount: resetprop-rs not found at $RP, skipping prop spoofing" > /dev/kmsg 2>/dev/null
    else
        . "$MODDIR/prop_table.sh"

        # Phase 1: Nuke PIF + ROM props (enforcer.rs:20-46)
        _nuke_prop() {
            if [ -z "$(getprop "$1" 2>/dev/null)" ]; then return; fi
            if [ "${1#persist.}" != "$1" ]; then
                "$RP" -p --nuke "$1" 2>/dev/null || "$RP" --hexpatch-delete "$1" 2>/dev/null || true
            else
                "$RP" --nuke "$1" 2>/dev/null || "$RP" --hexpatch-delete "$1" 2>/dev/null || true
            fi
        }

        echo "$NUKE_PIF" | while IFS= read -r _prop; do
            [ -n "$_prop" ] && _nuke_prop "$_prop"
        done

        echo "$NUKE_CUSTOM_ROM" | while IFS= read -r _prop; do
            [ -n "$_prop" ] && _nuke_prop "$_prop"
        done

        # Phase 2: Stealth-set props (enforcer.rs:4-18)
        echo "$STEALTH_PROPS" | while IFS='=' read -r _name _val; do
            [ -z "$_name" ] && continue
            _cur=$(getprop "$_name" 2>/dev/null)
            [ "$_cur" = "$_val" ] && continue
            "$RP" -st "$_name" "$_val" 2>/dev/null || true
        done

        # Phase 3: vbmeta config props (mod.rs:44-52)
        _vbsize=$("$BIN" config get brene.vbmeta_size 2>/dev/null)
        if [ -n "$_vbsize" ]; then
            _cur=$(getprop ro.boot.vbmeta.size 2>/dev/null)
            [ "$_cur" != "$_vbsize" ] && "$RP" -st ro.boot.vbmeta.size "$_vbsize" 2>/dev/null || true
        fi

        _vbhash=$("$BIN" config get brene.verified_boot_hash 2>/dev/null)
        if [ -n "$_vbhash" ]; then
            _cur=$(getprop ro.boot.vbmeta.digest 2>/dev/null)
            [ "$_cur" != "$_vbhash" ] && "$RP" -st ro.boot.vbmeta.digest "$_vbhash" 2>/dev/null || true
        fi

        echo "zeromount: prop spoofing applied (shell, stealth)" > /dev/kmsg 2>/dev/null
    fi
fi

# Performance tuning + input boost daemon (Rust-native, auto-detects device)
if [ "$("$BIN" config get perf.enabled 2>/dev/null)" = "true" ]; then
    "$BIN" perf &
    _bg_pids="$_bg_pids $!"
fi

# Magisk has no boot-completed callback — emulate it
if [ -z "$KSU" ] && [ -z "$APATCH" ]; then
    (
        while [ "$(getprop sys.boot_completed)" != "1" ]; do sleep 1; done
        sh "$MODDIR/boot-completed.sh"
    ) &
    _bg_pids="$_bg_pids $!"
fi

trap 'kill $_bg_pids 2>/dev/null; rm -f "$LOCKFILE"' EXIT
wait
